web:
  image: 'registry-vpc.cn-hangzhou.aliyuncs.com/bruke/hello-python:latest'
  command:
    - python
    - app.py
  restart: always
  environment:
    - LANG=C.UTF-8
    - GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
  ports:
    - 5000:5000
  links: 
    - redis
  depends_on:
    - redis
  labels:
    aliyun.scale: '1'
    aliyun.routing.port_5000: 'http://test.brukecui.com'
  
redis:
  image: 'redis:latest'
  restart: always
  environment:
    - 'REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-4.0.2.tar.gz'
    - REDIS_DOWNLOAD_SHA=b1a0915dbc91b979d06df1977fe594c3fa9b189f1f3d38743a2948c9f7634813
  expose:
    - 6379/tcp
  labels:
    aliyun.scale: '1'
  volumes:
    - /data